name = "HashpipeDatabufs"
uuid = "6e2f7c64-92ce-42bb-83af-8f0e5f56b763"
authors = ["David MacMahon <davidm@astro.berkeley.edu>"]
version = "0.0.1"

[deps]
InterProcessCommunication = "a7427343-1d15-5490-a218-bfcb7db836a2"

[compat]
InterProcessCommunication = "0.1.1"
